version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: worker
    env_file: .env
    depends_on:
      - redis
      - api

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  redis-data: 